# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TV_Program' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
  # Pods for TV_Program

  target 'TV_ProgramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TV_ProgramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
